server {
    listen 80;
    server_name _;

    gzip on;
    gzip_types application/json application/geo+json text/css application/javascript;
    gzip_min_length 1000;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8001;
        proxy_read_timeout 120s;
    }
}